export interface InboundTransmittalSubContractorV2Props {
  description: string;
  isDarkTheme: boolean;
  environmentMessage: string;
  hasTeamsContext: boolean;
  userDisplayName: string;
}
export interface InboundTransmittalSubContractorV2State {
  statusMessage: IMessage;
  dcc: any;
  dccId: any;
  owner: any;
  recievedDate: Date;
  subContractorNumber: any;
  poNumber: any;
  comments: any;
  projectName: any;
  projectNumber: any;
  revisionSettingsArray: any[];
  transmittalSettingsArray: any[];
  subContractorArray: any[];
  subContractorID: any;
  subContractor: any;
  purchaseOrderArray: any[];
  multidealer: boolean;
  transmittalOutlookDocumentArray: any[];
  documentIndexArray: any[];
  documentIndexID: any;
  documentIndexTitle: any;
  revisionCodingId: any;
  isIncrement: boolean;
  transmittalOutlookId: any;
  transmittalSettingsId: any;
  ownerId: any;
  showGrid: boolean;
  gridDocument: any[];
  externalDate: Date;
  externalComments: any;
  gridExternalDocument: any[];
  showExternalGrid: boolean;
  incrementSequenceNumber: any;
  transmittalSubContractorId: any;
  transmittalNo: string;
  searchDocuments: any[];
  items: any[];
  searchDiv: string;
  documentSelectedDiv: boolean;
  documentSelect: any;
  noSubContactor: string;
  inboundTransmittalHeaderId: any;
  sourceDocumentId: any;
  additionalDocumentId: any;
  transmittalInboundID: any;
  transmittalDate: Date;
  currentInboundDetailItem: any[];
  currentInboundAdditionalItem: any[];
  myfile: any;
  cancelConfirmMsg: string;
  confirmDialog: boolean;
  statusKey: string;
  validComment: string;
  validDocument: string;
  disableOutlook: boolean;
  validAdditionalComment: string;
  deleteConfirmMsg: string;
  tempDocIndexIDForDelete: any;
  submitDisable: any;
  viewDocument: any;
  validDocumentIndex: any;
  confirmDeleteDialog: boolean;
  accessDeniedMsgBar: string;
  access: string;
  loaderDisplay: string;
  checksend: string;
  uploadAdditionalDocumentError: string;
  uploadDocumentError: string;
  noDcc: string;
  notransmittal: string;
  legalId: string;
  poNumberID: any;
  title: any;

}

export interface IMessage {
  isShowMessage: boolean;
  messageType: number;
  message: string;
}
